/**
 * Turns single-line SVG fonts into the stroke data the liquid styles draw
 * with. `node scripts/extract-strokes.mjs`, then commit what it writes.
 *
 * A single-line font is a pen plotter's: every glyph is a set of centre
 * lines, not an outline, which is exactly what paste squeezed from a tube
 * follows. The fonts come from the hersheytext package (a dev dependency):
 * the Hershey fonts are public domain (see
 * src/components/reel-cover-maker/strokes/LICENSE.md). Pasty's own hand,
 * Drip, is drawn by scripts/drip-font.mjs instead.
 *
 * Each glyph is written as its advance and its strokes, every point in font
 * units (1000 to the em) with y pointing down from the baseline, and every
 * cubic curve flattened to short straight runs.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const FONTS = join(ROOT, "node_modules/hersheytext/svg_fonts");
const OUT = join(ROOT, "src/components/reel-cover-maker/strokes");

/** Which fonts, under which id, and what each is for. */
const WANTED = [
  { file: "HersheyScript1.svg", id: "script", note: "joined script, for Stickery's liquid words" },
  { file: "HersheySans1.svg", id: "sans", note: "plain capitals, for Spread" },
];

const ENTITIES = { amp: "&", quot: '"', lt: "<", gt: ">", apos: "'" };

function decode(text) {
  return text
    .replace(/&#x([0-9a-f]+);/gi, (_, hex) => String.fromCodePoint(Number.parseInt(hex, 16)))
    .replace(/&#(\d+);/g, (_, dec) => String.fromCodePoint(Number(dec)))
    .replace(/&(amp|quot|lt|gt|apos);/g, (_, name) => ENTITIES[name]);
}

/** An SVG path of M, L and C commands as polylines, curves cut into `steps` straight runs. */
function polylines(d, steps = 8) {
  const tokens = d.match(/[MLC]|-?\d*\.?\d+(?:e-?\d+)?/gi) ?? [];
  const lines = [];
  let line = null;
  let command = null;
  let x = 0;
  let y = 0;
  let i = 0;
  const num = () => Number(tokens[i++]);
  while (i < tokens.length) {
    if (/^[MLC]$/i.test(tokens[i])) command = tokens[i++].toUpperCase();
    if (command === "M") {
      x = num();
      y = num();
      line = [[x, y]];
      lines.push(line);
      command = "L";
    } else if (command === "L") {
      x = num();
      y = num();
      line.push([x, y]);
    } else if (command === "C") {
      const [x1, y1, x2, y2, x3, y3] = [num(), num(), num(), num(), num(), num()];
      for (let s = 1; s <= steps; s += 1) {
        const t = s / steps;
        const u = 1 - t;
        line.push([
          u * u * u * x + 3 * u * u * t * x1 + 3 * u * t * t * x2 + t * t * t * x3,
          u * u * u * y + 3 * u * u * t * y1 + 3 * u * t * t * y2 + t * t * t * y3,
        ]);
      }
      x = x3;
      y = y3;
    } else {
      throw new Error(`Unexpected path token ${tokens[i]} in ${d.slice(0, 40)}`);
    }
  }
  return lines;
}

mkdirSync(OUT, { recursive: true });
const index = [];

for (const { file, id, note } of WANTED) {
  const svg = readFileSync(join(FONTS, file), "utf8");
  const name = svg.match(/font-family="([^"]+)"/)?.[1] ?? id;
  const upm = Number(svg.match(/units-per-em="([\d.]+)"/)?.[1] ?? 1000);
  const fallbackAdvance = Number(svg.match(/<font [^>]*horiz-adv-x="([\d.]+)"/)?.[1] ?? 400);
  const license = svg.match(/License:\s+([^\n]+)/)?.[1]?.trim() ?? "Public domain";
  const glyphs = {};
  for (const match of svg.matchAll(/<glyph\b([^>]*?)\/?>/g)) {
    const attributes = match[1];
    const unicode = attributes.match(/unicode="([^"]*)"/)?.[1];
    if (unicode === undefined) continue;
    const character = decode(unicode);
    // No dash glyphs: the source holds no en or em dash, and a typed one is drawn as a hyphen.
    if (character === "\u2013" || character === "\u2014") continue;
    const advance = Number(attributes.match(/horiz-adv-x="([\d.]+)"/)?.[1] ?? fallbackAdvance);
    const d = attributes.match(/\sd="([^"]*)"/)?.[1] ?? "";
    // Font units with y up become y down from the baseline, rounded to a unit.
    const strokes = polylines(d)
      .map((line) => line.flatMap(([px, py]) => [Math.round(px), Math.round(-py)]))
      .filter((flat) => flat.length >= 4 || flat.length === 2);
    glyphs[character] = [Math.round(advance), strokes];
  }
  const body = [
    "// Generated by scripts/extract-strokes.mjs. Do not edit by hand.",
    `// ${name}: ${license}. See LICENSE.md beside this file.`,
    'import type { StrokeFontData } from "@/components/reel-cover-maker/strokes/types";',
    "",
    `export const ${id.toUpperCase()}: StrokeFontData = ${JSON.stringify({ id, name, upm, glyphs })};`,
    "",
  ].join("\n");
  writeFileSync(join(OUT, `${id}.ts`), body);
  index.push({ id, name, license, note, glyphs: Object.keys(glyphs).length });
  console.log(`${id}: ${Object.keys(glyphs).length} glyphs, ${(body.length / 1024).toFixed(0)} KB`);
}

console.log(JSON.stringify(index, null, 1));
