/**
 * Draws "Goo", the hand Stickery's drawn lettering is squeezed along, and
 * writes it as stroke data. `node scripts/goo-font.mjs`, then commit what it
 * writes.
 *
 * Goo is drawn after Main Sticker 2's "aren't" and "what": a round,
 * running hand, its curves full, drawn to be laid in paste thin through the
 * stroke and heavy at its ends, the letters run into each other. A w is
 * two round bowls with a low,
 * round peak between them, an a a lying lens under a roof, an e a loop on
 * a rising bar; a stem that ends
 * on the baseline runs on to the right, so the next letter can run into
 * it; a t is tall and curved, its crossbar high and rising, for the swash
 * a word's last t swings out. Only the lowercase (and a shorter
 * apostrophe, a bead) is Goo's own: capitals, figures and other marks are Drip's
 * (scripts/drip-font.mjs), which share its heights.
 *
 * Authored as Drip is: points the stroke passes through, smoothed by a
 * centripetal Catmull and Rom spline, `*` a corner and a closing `z` a loop,
 * y up from the baseline in units of 1000 to the em (x-height 480,
 * ascenders 760, descenders 260), written y down.
 *
 * Goo is this project's own drawing, under the project's licence.
 */

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildGlyphs, GLYPHS as DRIP } from "./drip-font.mjs";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const OUT = join(ROOT, "src/components/reel-cover-maker/strokes/goo.ts");

/** A bowl, counterclockwise from its top right, for a, d, g and q: `w` wide. */
const bowl = (w) => `${w - 10},400 ${w - 90},476 ${w - 200},474 ${w - 290},400 ${w - 320},250 ${w - 290},95 ${w - 210},15 ${w - 110},15 *${w - 25},140`;

/** Advance, then strokes. */
const LOWER = {
  a: [440, ["70,455 190,468 300,445 355,400 352,220 345,60 380,8 450,0", "350,330 240,250 120,160 45,95 75,25 170,0 280,12 350,60"]],
  b: [420, ["90,760 80,380 75,0", "80,300 160,440 265,480 355,400 380,240 340,80 240,5 140,15 *80,90"]],
  c: [380, ["340,390 265,476 155,470 70,385 40,240 70,85 160,5 260,10 345,90"]],
  d: [440, [bowl(360), "350,760 345,380 352,90 390,15 445,10"]],
  e: [400, ["*55,215 *345,300 335,410 250,478 145,470 65,385 40,235 75,85 170,5 275,15 355,90"]],
  f: [320, ["300,690 245,765 170,750 135,650 125,300 125,0", "35,455 275,468"]],
  g: [420, [bowl(360), "355,480 355,-110 315,-215 215,-255 110,-225 55,-150"]],
  h: [400, ["130,760 95,420 50,0", "70,200 140,380 225,470 290,420 310,250 300,60 340,5 420,0"]],
  i: [220, ["110,480 105,250 110,80 145,10 205,5", "120,690"]],
  j: [240, ["160,480 160,-130 120,-225 35,-255", "170,690"]],
  k: [410, ["95,760 85,380 75,0", "*335,480 *85,215 *375,0"]],
  l: [240, ["110,760 100,300 110,90 150,10 220,5"]],
  m: [620, ["70,480 65,240 60,0", "65,320 125,450 205,480 275,420 295,300 290,0", "290,320 350,450 435,480 510,420 530,300 530,90 560,15 620,10"]],
  n: [440, ["70,480 65,240 60,0", "65,300 140,440 245,480 330,430 355,300 355,90 385,15 445,10"]],
  o: [410, ["205,480 85,425 40,240 85,55 205,0 325,55 370,240 325,425 205,480 z"]],
  p: [420, ["80,480 75,100 70,-260", "80,300 160,440 265,480 355,400 380,240 340,80 240,5 140,15 *80,90"]],
  q: [420, [bowl(360), "355,480 350,100 350,-260"]],
  r: [340, ["70,470 65,240 55,0", "68,400 140,450 240,468 330,480"]],
  s: [360, ["320,410 245,478 140,472 65,405 80,305 195,245 300,175 320,85 250,12 135,0 55,35 20,85"]],
  t: [300, ["175,760 172,560 160,330 135,120 110,-60", "45,585 290,625"]],
  u: [440, ["65,480 60,170 95,50 185,0 275,40 335,160 *350,480 345,250 352,90 390,15 445,10"]],
  v: [400, ["40,470 75,240 *200,0 310,230 365,470"]],
  w: [540, ["50,470 35,250 65,70 135,0 200,60 232,190 248,228 263,190 285,60 350,0 420,60 462,250 465,470"]],
  x: [400, ["*45,480 *355,0", "*355,480 *45,0"]],
  y: [430, ["65,480 60,170 95,50 185,0 275,40 335,160 *350,480 352,-110 310,-215 210,-255 105,-225 50,-150"]],
  z: [390, ["*45,480 *340,480 *45,0 *350,0"]],
  // An apostrophe one small bead, where Drip's stroke, lifted with the ascenders, swelled into a blob.
  "'": [150, ["75,600"]],
};

/** Every lowercase letter drawn this much wider than authored, as Main Sticker 2's are for their height. */
const WIDE = 1.1;

const widened = (stroke) =>
  stroke.replace(/(\*?)(-?\d+),(-?\d+)/g, (_, corner, x, y) => `${corner}${Math.round(Number(x) * WIDE)},${y}`);

const glyphs = buildGlyphs({
  ...DRIP,
  ...Object.fromEntries(Object.entries(LOWER).map(([c, [advance, strokes]]) => [c, [Math.round(advance * WIDE), strokes.map(widened)]])),
});
const data = { id: "goo", name: "Goo", upm: 1000, glyphs };
writeFileSync(
  OUT,
  `// Generated by scripts/goo-font.mjs. Do not edit by hand.\n// Goo: this project's own drawing, under its licence.\nimport type { StrokeFontData } from "@/components/reel-cover-maker/strokes/types";\n\nexport const GOO: StrokeFontData = ${JSON.stringify(data)};\n`,
);
console.log(`Goo: ${Object.keys(glyphs).length} glyphs`);
